[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "osmnx>=2.1.0",
    "pyproj>=3.7.2",
    "setiptah-roadgeometry",
    "setiptah-roadgeometry-matching",
    "shapely>=2.1.2",
    "uvicorn[standard]>=0.46.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.uv.sources]
setiptah-roadgeometry = { path = "../../setiptah-roadgeometry", editable = true }
setiptah-roadgeometry-matching = { path = "../../setiptah-roadgeometry-matching", editable = true }
